version: '3.8'
services:
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
    container_name: mongodb
    volumes:
      - data:/data
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_DATABASE=mytestdb
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081

volumes:
  data: { }

networks:
  default:
    name: mongodb_network
