
server:
  port: 9991

spring:
#  redis:
#    host: localhost
#    port: 16379
  jackson:
    serialization:
      indent_output: true

management:
  health:
    defaults:
      enabled: true
    redis:
      enabled: true

app:
  redis-group:
    -
      host: localhost
      port: 16379
      password: ''
      database: 0
    -
      host: localhost
      port: 16380
      password: ''
      database: 1
    -
      host: localhost
      port: 16381
      password: ''
      database: 2

