version: "3.7"
services:

  concurrency-v2-redis:
    image: redis:6.2.7
    labels:
      - "name=redis"
      - "mode=standalone"
    environment:
      - REDIS_REPLICATION_MODE=master
    ports:
      - "17380:6379"

  concurrency-v2-mysql:
    image: library/mysql:8.0
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=testdb
    ports:
      - "13311:3306"
