server:
  port: 9992

spring:
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.format_sql: true
      hibernate.use_sql_comments: true

  # h2 를 web console 로 보고 싶은 경우
  h2:
    console:
      enabled: true
      path: /h2-console       # localhost:9992/h2-console 접근

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb   # jdbc url 을 여기로 접속한다.
    username: sa
    password:

  # .sql 파일을 통해 데이터 초기화 하고 싶은 경우에 사용할 수 있도록 한다,
  sql:
    init:
      platform: h2
      username: sa
      password:
