
logging:
  level:
    org.quartz: INFO
    com.zaxxer.hikari: DEBUG

server:
  port: 44440

spring:
  # 별도 스프링에서 데이터 소스를 정의할 필요가 없다. : 사용하지 않아서 hikari 만 의존성 추가. 왜 jdbc 를 추가했을까...
#  datasource:
#    url: jdbc:mysql://dockerhost:13350/testdb
#    username: root
#    password: rootpass
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    hikari:
#      # https://github.com/brettwooldridge/HikariCP#configuration-knobs-baby
#      maximum-pool-size: 8
#      connection-timeout: 25000 # 25sec

  quartz:
    jdbc:
      initialize-schema: always
      platform: mysql

    # job-store-type: memory
    job-store-type: jdbc
    scheduler-name: pasudo-scheduler-1
    overwrite-existing-jobs: true

    properties:
      # http://www.quartz-scheduler.org/documentation/quartz-2.3.0/configuration/#choose-a-topic: 참고
      org.quartz.threadPool.threadCount: 5

      # scheduler
      org.quartz.scheduler.threadName: psd-thr
      org.quartz.scheduler.instanceName: psd-ins
      org.quartz.scheduler.instanceId: AUTO

      # jobStore
      org.quartz.jobStore.class: org.quartz.impl.jdbcjobstore.JobStoreTX
      org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
      org.quartz.jobStore.useProperties: true # jobDetail 의 jobData 컬럼을 텍스트로 넣기 위한 옵션 (유연성이 더 큼)
      org.quartz.jobStore.isClustered: true # 쿼츠 클러스터 설정 여부
      org.quartz.jobStore.clusterCheckinInterval: 10000 # milli sec 주기로 클러스터 상태여부 체크
      org.quartz.jobStore.dataSource: quartzDataSource

      # dataSource
      org.quartz.dataSource.quartzDataSource.driver: com.mysql.cj.jdbc.Driver
      org.quartz.dataSource.quartzDataSource.URL: jdbc:mysql://dockerhost:13350/testdb
      org.quartz.dataSource.quartzDataSource.user: root
      org.quartz.dataSource.quartzDataSource.password: rootpass

      # https://github.com/quartz-scheduler/quartz/wiki/How-to-Use-DB-Connection-Pool
      # datasource connection pool hikari 사용
      org.quartz.dataSource.quartzDataSource.provider: hikaricp # hikaricp 없으면 다른 provider 를 임포트 해주던가 해야함. (아니면 기본으로 C3p0Pooling 이 필요함)

      # http://www.quartz-scheduler.org/documentation/quartz-2.3.0/configuration/ConfigDataSources.html
      # hikari 사용시, 관련 속성 사용 가능. https://github.com/brettwooldridge/HikariCP#configuration-knobs-baby
      # hikari 속성 카멜케이스 그대로 기입해야한다.
      org.quartz.dataSource.quartzDataSource.maximumPoolSize: 11
      org.quartz.dataSource.quartzDataSource.connectionTimeout: 20000 # 20sec (default : 30sec)
      org.quartz.dataSource.quartzDataSource.validationTimeout: 5000 # 5sec


  mail:
    host: smtp.naver.com
    port: 587
    username: pasudo123@naver.com
    # naver password 참고 : https://help.naver.com/support/contents/contents.help?serviceNo=532&categoryNo=11047
    password:
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

## job 식별 아이덴티티
custom-worker:
  simple-cron-worker:
    id: simple-test-03
    job-group: simple-job-group
    job-desc: "테스트를 위한 잡명세"
    trigger-group: simple-trigger-group
    trigger-desc: "테스트를 위한 트리거 명세"
    cron-expression: "0/5 * * * * ?"




