version: "3.7"
services:
  redis:
    image: idock.daumkakao.io/airport-docker/redis5.0
    labels:
      - "name=redis"
      - "mode=standalone"
    environment:
      - REDIS_REPLICATION_MODE=master
    ports:
      - "6379:6379"